package GUI;

public enum TrackType {
    SINGLE_STRAIGHT,
    DOUBLE_STRAIGHT,
    RADIUS_1_SINGLE_CURVE,
    RADIUS_2_SINGLE_CURVE,
    RADIUS_3_SINGLE_CURVE,
    RADIUS_1_DOUBLE_CURVE,
    RADIUS_2_DOUBLE_CURVE,
    RADIUS_3_DOUBLE_CURVE,
    LEFT_HAND_POINT,
    RIGHT_HAND_POINT,
    LEFT_HAND_CROSSOVER,
    RIGHT_HAND_CROSSOVER,
    POINT_SWITCH
}
